### ISSUE TITLE
Group buttons within the menu bar

### ISSUE THREAD

**Issue by Kajvdh** [tothepoint-itco/coordinatorentool#27]
Each context should have its own dropdown with the action buttons that are relevant to that context.

**Comment by ButrintZymberi** [comment]
What context terminology should I use for: 
- Bedienden/contracten 
- Opdrachten/Bestelbonnen/Akkoorden

**Comment by Kajvdh** [comment]
@heynist

**Comment by heynist** [comment]
Graag deze menu structuur implementeren ajb:

HR

> Consultants (huidige 'Bedienden')
> Contracten

Planning

> Opdrachten
> Akkoorden
> Bestelbonnen
> Overzicht (huidige 'Planning')

Administratie

> Beheerders
> Business Units

Logout
