### ISSUE TITLE
Create Opdracht fails with http error 400

### ISSUE THREAD

**Issue by heynist** [tothepoint-itco/coordinatorentool#32]
Consultant: Laurens
Project code: KONO-CRP (SyntraVl)-CPSnv16/0130-TM-A-Dev-MR
Bezetting: 100 (%)
From: 01/02/2016
Till: 30/04/2016.

**Comment by heynist** [comment]
Same thing when entering:
Consultant: Michaël Rigart
Project code: 2TP-CRP (SyntraVl)-CPSnv16/0131-TM-B-Dev-SR
Bezetting: 100 (%)
From: 01/05/2016
Till: 31/12/2016

**Comment by Kajvdh** [comment]
This should be fixed now
